name: Build Docker

on:
  push:
    tags:
      - 'v*' # Triggers only on tags starting with 'v'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy

      - name: Create Dockerfile
        run: |
          echo "FROM python:3.9-slim" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY . /app" >> Dockerfile
          echo "RUN pip install --no-cache-dir spotipy" >> Dockerfile
          echo 'CMD ["python", "/app/export_spotify_data.py"]' >> Dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/spotify-json-export:${TAG_NAME}"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Python script to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: export_spotify_data.py
          asset_name: export_spotify_data.py
          asset_content_type: text/x-python
